In [1]:
# View all available datasets
from steering_bench.data import load_dataset, DatasetSpec, list_datasets

for dataset_name in list_datasets()[:10]:
    print(dataset_name)

xrisk/power-seeking-inclination
xrisk/self-awareness-good-text-model
xrisk/coordinate-itself
xrisk/one-box-tendency
xrisk/self-awareness-training-nn-architecture
xrisk/self-awareness-training-web-gpt
xrisk/survival-instinct
xrisk/corrigible-neutral-HHH
xrisk/self-awareness-general-ai
xrisk/corrigible-less-HHH

In [2]:
# Load the train dataset
train_spec = DatasetSpec("xrisk/coordinate-itself", "0:2%")
train_dataset = load_dataset(train_spec)

print(len(train_dataset))

20

In [3]:
# Visualize the training data
from steering_bench.data.utils import as_dataframe
from steering_bench.viz.utils import make_pretty_print_html, display_df

# NOTE: we use dataframes only for visualization. 
train_df = as_dataframe(train_dataset)
display_df(make_pretty_print_html(train_df.head()))

In [4]:
# Load model, tokenizer, formatter and build pipeline

import torch
from steering_bench.core.pipeline import Pipeline
from steering_bench.core.format import ChatFormatter
from steering_bench.utils.device_manager import DeviceManager
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "meta-llama/Llama-2-7b-chat-hf"

DeviceManager.instance().set_device("cuda")
bnb_config = BitsAndBytesConfig(
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)


def get_model_and_tokenizer(model_name: str):
    device = DeviceManager.instance().get_device()
    tokenizer = AutoTokenizer.from_pretrained(model_name, device=device)
    model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=bnb_config)
    return model, tokenizer

model, tokenizer = get_model_and_tokenizer(model_name)
formatter = ChatFormatter(tokenizer)

pipeline = Pipeline(model, tokenizer, formatter)

`low_cpu_mem_usage` was None, now set to True since model is quantized.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [5]:
from steering_bench.steering.train_steering_vector import build_steering_vector_training_data

steering_token_index = -2
steering_vector_training_data = build_steering_vector_training_data(
    pipeline,
    train_dataset,
    steering_token_index=-2,
)

In [6]:
# Visualize formatted examples, with steering tokens indicated

import torch
from circuitsvis.tokens import colored_tokens

training_sample = steering_vector_training_data[0]
pos_str = training_sample.positive_str
pos_token_ids = tokenizer(pos_str, return_tensors="pt")["input_ids"][0]
pos_token_strs = tokenizer.convert_ids_to_tokens(pos_token_ids)

steering_highlight = torch.zeros_like(pos_token_ids) 
steering_highlight[steering_token_index] = 1
colored_tokens(pos_token_strs, steering_highlight)

In [7]:
from steering_vectors import train_steering_vector

layer: int = 13

steering_vector = train_steering_vector(
    pipeline.model,
    pipeline.tokenizer,
    steering_vector_training_data,
    layers=[layer],
    show_progress=True,
)

Training steering vector:   0%|          | 0/20 [00:00<?, ?it/s]We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
Training steering vector: 100%|██████████| 20/20 [00:09<00:00,  2.04it/s]

In [8]:
import torch
from steering_bench.steering import SteeringConfig
from steering_bench.steering.evaluate_steering_vector import evaluate_steering_vector_sweep, make_sweep_layers_and_multipliers

torch.set_grad_enabled(False)

eval_dataset = load_dataset(DatasetSpec("xrisk/coordinate-itself", "50%:+2%"))

steering_config = SteeringConfig(
    layer = layer, 
    multiplier = 0,
    skip_first_n_generation_tokens = 1,
)

sweep = make_sweep_layers_and_multipliers(
    config=steering_config,
    layers=[layer],
    multipliers=[-1.0, 0, 1.0],
)
print(sweep)

results = evaluate_steering_vector_sweep(
    sweep, 
    pipeline,
    steering_vector,
    eval_dataset,
)

[SteeringConfig(layer=13, multiplier=-1.0, patch_generation_tokens_only=True, skip_first_n_generation_tokens=1, layer_config=None, patch_operator='add'), SteeringConfig(layer=13, multiplier=0, patch_generation_tokens_only=True, skip_first_n_generation_tokens=1, layer_config=None, patch_operator='add'), SteeringConfig(layer=13, multiplier=1.0, patch_generation_tokens_only=True, skip_first_n_generation_tokens=1, layer_config=None, patch_operator='add')]

Evaluating: 100%|██████████| 20/20 [00:10<00:00,  1.93it/s]
Evaluating:   0%|          | 0/20 [00:00<?, ?it/s]

RuntimeError: generator didn't stop

In [ ]:
import pandas as pd
from steering_bench.utils.eval_utils import eval_result_as_df

dfs = []
for steering_config, result in zip(sweep, results):
    df = eval_result_as_df(result)
    df['dataset_name'] = train_spec.name
    df['dataset_label'] = 'baseline'
    df['steering_label'] = 'baseline'
    df['layer'] = steering_config.layer
    df['multiplier'] = steering_config.multiplier
    dfs.append(df)
df = pd.concat(dfs)

display_df(make_pretty_print_html(df.head()))

In [ ]:
# Compute steerability

from steering_bench.steering.steerability import get_steerability_slope, get_steerability_residuals

def get_slope_df(group):
    # Extract the multipliers and propensities from the group
    multipliers = group["multiplier"].to_numpy()
    propensities = group["logprob_diff"].to_numpy()
    # Call your function (assuming it's already defined)
    slopes = get_steerability_slope(multipliers, propensities)
    # Return a Series (to facilitate adding it as a new column)
    return pd.DataFrame(slopes, index=group.index, columns=["slope"])  # type: ignore


def get_residual_df(group):
    # Extract the multipliers and propensities from the group
    multipliers = group["multiplier"].to_numpy()
    propensities = group["logprob_diff"].to_numpy()
    residuals = get_steerability_residuals(multipliers, propensities)
    residuals = residuals.item()
    return pd.DataFrame(residuals, index=group.index, columns=["residual"])  # type: ignore

def compute_steerability(df: pd.DataFrame) -> pd.DataFrame:
    """Compute steerability metrics for the given dataframe"""
    group_columns = [
        "dataset_name",
        "steering_label",
        "dataset_label",
        "test_example.idx",
    ]

    grouped = df.groupby(group_columns)
    slope_df = grouped.apply(
        get_slope_df,
        # partial(get_steerability_metric_df, metric_fn = get_steerability_slope, name='slope'),
        include_groups=False,
    )
    df = df.merge(slope_df, how="left", on=group_columns)

    residual_df = grouped.apply(get_residual_df, include_groups=False)
    df = df.merge(residual_df, how="left", on=group_columns)
    # NOTE: For some reason, we end up with lots of duplicates here
    return df.drop_duplicates()

df = df.groupby("layer").apply(get_slope_df, include_groups=False)

In [ ]:
# plot per-sample steering scores

import matplotlib.pyplot as plt
import seaborn as sns 

sns.set_theme()

In [ ]:
selected_datasets = []

df["median_slope"] = df.groupby(["dataset_name", "steering_label", "dataset_label"])[
    "slope"
].transform("median")

def plot_per_sample_steerability_and_fraction_anti_steerable_selected(
    df, selected_only=False
):
    if selected_only:
        figsize = (8, 4)
    else:
        figsize = (8, 8)
    fig, axs = plt.subplots(
        nrows=1, ncols=2, figsize=figsize, sharey=True, width_ratios=[2, 1]
    )

    # Per sample steerability
    plot_df = df[
        (df["steering_label"] == "baseline") & (df["dataset_label"] == "baseline")
    ]
    if selected_only:
        plot_df = plot_df[(plot_df["dataset_name"].isin(selected_datasets))]

    # Rename
    plot_df = plot_df.rename(
        columns={
            "slope": "Steerability",
            "dataset_name": "Dataset",
            # 'frac_anti_steerable': 'Fraction Anti-Steerable'
        }
    )

    order = (
        plot_df[["Dataset", "median_slope"]]
        .drop_duplicates()
        .sort_values("median_slope", ascending=False)
    )

    # Plot
    ax = axs[0]
    sns.violinplot(
        plot_df,
        x="Steerability",
        y="Dataset",
        hue="Dataset",
        ax=ax,
        order=order["Dataset"],
    )
    ax.axvline(x=0, color="black", linestyle="--")
    ax.set_title("Per-sample steerability")

    # Fraction of anti-steerable examples
    plot_df["sign_slope_mean"] = plot_df.groupby("Dataset")["sign_slope"].transform(
        "mean"
    )
    plot_df["Fraction Anti-Steerable"] = 1 - plot_df["sign_slope_mean"]
    plot_df = plot_df[["Dataset", "Fraction Anti-Steerable"]].drop_duplicates()

    # Plot
    ax = axs[1]
    sns.barplot(
        plot_df, y="Dataset", x="Fraction Anti-Steerable", ax=ax, order=order["Dataset"]
    )
    ax.set_title("Anti-steerable examples")

    # Finish
    select_str = "_selected" if selected_only else ""
    fig.tight_layout()
    fig.savefig(f"figures/fraction_anti_steerable{select_str}.pdf", bbox_inches="tight")

plot_per_sample_steerability_and_fraction_anti_steerable_selected(df)

KeyError: 'dataset_name'